# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/btoffoli/projects/cpp/cmake_test_library_test1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/btoffoli/projects/cpp/cmake_test_library_test1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/btoffoli/projects/cpp/cmake_test_library_test1/CMakeFiles /home/btoffoli/projects/cpp/cmake_test_library_test1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/btoffoli/projects/cpp/cmake_test_library_test1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named animals

# Build rule for target.
animals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 animals
.PHONY : animals

# fast build rule for target.
animals/fast:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/build
.PHONY : animals/fast

src/animals.o: src/animals.cpp.o

.PHONY : src/animals.o

# target to build an object file
src/animals.cpp.o:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/animals.cpp.o
.PHONY : src/animals.cpp.o

src/animals.i: src/animals.cpp.i

.PHONY : src/animals.i

# target to preprocess a source file
src/animals.cpp.i:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/animals.cpp.i
.PHONY : src/animals.cpp.i

src/animals.s: src/animals.cpp.s

.PHONY : src/animals.s

# target to generate assembly for a file
src/animals.cpp.s:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/animals.cpp.s
.PHONY : src/animals.cpp.s

src/main_animals.o: src/main_animals.cpp.o

.PHONY : src/main_animals.o

# target to build an object file
src/main_animals.cpp.o:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/main_animals.cpp.o
.PHONY : src/main_animals.cpp.o

src/main_animals.i: src/main_animals.cpp.i

.PHONY : src/main_animals.i

# target to preprocess a source file
src/main_animals.cpp.i:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/main_animals.cpp.i
.PHONY : src/main_animals.cpp.i

src/main_animals.s: src/main_animals.cpp.s

.PHONY : src/main_animals.s

# target to generate assembly for a file
src/main_animals.cpp.s:
	$(MAKE) -f CMakeFiles/animals.dir/build.make CMakeFiles/animals.dir/src/main_animals.cpp.s
.PHONY : src/main_animals.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... animals"
	@echo "... edit_cache"
	@echo "... src/animals.o"
	@echo "... src/animals.i"
	@echo "... src/animals.s"
	@echo "... src/main_animals.o"
	@echo "... src/main_animals.i"
	@echo "... src/main_animals.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

